server:
  port: 8088
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis-plus:
  mapper-locations: classpath:com/baizhi/cmfz/dao/*Mapper.xml

